export { default as CompleteRegistrationPage } from './complete-registration.jsx'
export { default as CreateAccountPage } from './create-account.jsx'
export { default as LoginPage } from './login.jsx'
export { default as PasswordResetRequestPage } from './password-reset-request.jsx'
export { default as PasswordUpdatePage } from './password-update.jsx'
export { default as SafeModePage } from './safe-mode.jsx'
export { default as DownloadPage } from './download-html.jsx'
